### ISSUE TITLE
Unable to complete DelayD experiments.

### ISSUE THREAD

**Issue by vinaybabug** [vinaybabug/RDMTk#1]
Experiment progress does not reach 100% after completion of all the trials. Its stuck at < 100%.

**Comment by Praneetsoni** [comment]
Sir can you please elaborate a bit more on the issue..what is happening right now is that on selecting an option for last question, the user is taken to the end page and progress bar is not updated to show 100% because the user is anyways being taken to the end prompt, which is a separate page.

**Comment by vinaybabug** [comment]
Hi Praneet,

For some reason this section of code was causing problem

document.getElementById("que1").innerHTML =arr[ranNums[clicks]]['option_a'];				document.getElementById("que2").innerHTML =arr[ranNums[clicks]]['option_b'];

and arr.length needs to be checked against < clicks -2. Experiment was not storing all trials data..instead only total trial# - 1 was getting stored. 

I will upload fixed code and close this bug.

**Comment by vinaybabug** [comment]
@Praneetsoni can you please check modified changes and confirm its the problem is fixed and task is working as intended.

**Comment by Praneetsoni** [comment]
yes sir..the updated code is working as expected and without any problems.
