### ISSUE TITLE
Session handling and logout on in activity

### ISSUE THREAD

**Issue by vinaybabug** [vinaybabug/RDMTk#7]
Application dashboard aspect does not implement logout on in activity feature yet. Also, session handling needs to be rechecked.

**Comment by Praneetsoni** [comment]
I have implemented the automatic log-out , current inactivity period for automatic logout has been set as 10 min.But that can be changed by changing the value of 'minsToLogout' variable in dashboard_master. 
Also, what exactly needs to be checked about session handling? currently the lifetime of a session has been specified at 120 mins.

**Comment by vinaybabug** [comment]
I think 10min should be more like 3-5 min and I am not sure what would be correct session length lets keep it as it is. We are not checking anything is session handling later on when analysis is implemented we need session handling for sure. I wanted to make sure we have such a feature to store user specific data during particular session.

Date: Sun, 31 Jan 2016 04:21:39 -0800
